### ISSUE TITLE
[Feature Request]  Quantizer mini - config with own forked firmware

### ISSUE THREAD

**Issue by tcastelly** [sekigon-gonnoc/qmk_firmware#60]
## Feature Request Type

- [ ] Core functionality
- [x] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description
Be able to use his own Quantizer Mini fork 

I've defined [custom tap dance](https://github.com/tcastelly/qmk_firmware_corne_ec/blob/custom_tap_dance/keyboards/sekigon/keyboard_quantizer/mini/keymaps/tcy_full/tapdance.h#L61), I would want to use them like this, of course it's not possible:

```yaml
- application:
    keymaps:
      - layer:
          id: 0
          keys:
            KC_CAPS: TD(TD_TAB)
```
![image](https://github.com/sekigon-gonnoc/qmk_firmware/assets/37597737/d0fa521e-92e3-4c46-9f9e-6bbdb063a8bd)

Is there an easy way to do this?

Thank you very much.
